"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'
# [pastel, pastel_brite, catppuccin_mocha]

format = """
[╭](gray)\
[](bg0)\
$os\
$username\
[ ](bg0)\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$kotlin\
$nodejs\
$nim\
$php\
$python\
$rust\
$scala\
$time\
$cmd_duration\
$line_break\
[╰](gray)\
$character
"""

[username]
disabled = false
show_always = true
style_user = "bg:bg0 fg:text"
style_root = "bg:bg0 fg:text"
# symbol = "󰀄"
format = '[$user ]($style)'

[os]
disabled = false
style = "bg:bg0 fg:text"

[os.symbols]
Windows = "  "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[directory]
disabled = false
style = "bg:bg1 fg:text"
# home_symbol = ""
format = "[](bg1)[  $path ]($style)[ ](bg1)"
truncation_length = 3
truncation_symbol = "…/"

# Shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "/Documents" = "/󰈙 "
# "/Downloads" = "/ "
# "/Music" = "/ "
# "/Pictures" = "/ "
# "/Videos" = "/ "
# "/Audios" = "/ "
# "/GitHub" = "/ "
# "/.config" = "/ "
# "/Develop" = "/󰲋 "
# Keep in mind that the order matters. For example:
# "/Important Documents" = "/󰈙 "
# will not be replaced, because "/Documents" was already substituted before.
# So either put "/Important Documents" before "/Documents" or use the substituted version:
# "/Important 󰈙 " = "/󰈙 "

[time]
disabled = false
time_format = "%R"
style = "bg:bg4 fg:text"
format = '[](bg4)[  $time ]($style)[ ](bg4)'

[cmd_duration]
disabled = false
show_milliseconds = true
show_notifications = true
min_time = 100
min_time_to_notify = 45000
format = "[ ](bg5)[  in $duration ]($style)[](bg5)"
style = "fg:lavender"

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'

[git_branch]
symbol = ""
style = "bg:bg2 fg:text"
format = '[](bg2)[ $symbol $branch ]($style)[ ](bg2)'

[git_status]
disabled = false
ahead = " $count "
behind = " $count "
deleted = "﫧 $count "
diverged = " $count "
stashed = " $count "
modified = " $count "
staged = " $count "
renamed = " $count "
untracked = " $count "
style = "bg:bg2 fg:text"
format = '[](bg2)[($all_status$ahead_behind)]($style)[ ](bg2)'

[conda]
symbol = ""
style = "bg:bg4 fg:text"
format = '[ $symbol ($environment) ]($style)'
ignore_base = false

[docker_context]
symbol = ""
style = "bg:bg4 fg:text"
format = '[ $symbol ($context) ]($style)'

[pixi]
style = "bg:bg4 fg:text"
format = '[ $symbol ($version) ($environment) ]($style)'

[c]
symbol = ""
style = "bg:bg3 fg:text"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[elixir]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[elm]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[golang]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[gradle]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[haskell]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[java]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[julia]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[kotlin]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[nodejs]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[nim]
symbol = "󰆥"
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[php]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[python]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[rust]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'


[scala]
symbol = ""
style = "bg:bg3 fg:text"
format = '[](bg3)[ $symbol ($version) ]($style)[ ](bg3)'

[palettes.pastel]
bg0 = '90'
bg1 = '168'
bg2 = '216'
bg3 = '110'
bg4 = '30'
bg5 = '24'
text = '231'
lavender = '147'
red = '161'
yellow = '222'
green = '77'
white = '231'
gray = '242'
black = '16'

[palettes.pastel_brite]
bg0 = '183'
bg1 = '211'
bg2 = '216'
bg3 = '111'
bg4 = '116'
bg5 = '74'
text = '16'
lavender = '147'
red = '161'
yellow = '222'
green = '77'
white = '231'
gray = '242'
black = '16'

[palettes.catppuccin_mocha]
bg0 = '211'
bg1 = '216'
bg2 = '223'
bg3 = '151'
bg4 = '117'
bg5 = '147'
text = '16'
lavender = '147'
red = '161'
yellow = '222'
green = '77'
white = '231'
gray = '242'
black = '16'
